#version: '3.8'
services:
  app:
    build: .
    environment:
      - RECEIPT_BOT_TOKEN=${RECEIPT_BOT_TOKEN}
      - FNS_TOKEN=${FNS_TOKEN}
      - MYSQL_DS_PASSWORD=${MYSQL_DS_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/receipts_db
    depends_on:
      mysql:
        condition: service_healthy
    #restart: on-failure

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DS_PASSWORD}
      MYSQL_DATABASE: receipts_db
    #ports:
    #  - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 40s

volumes:
  mysql_data: